name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main # Déclenche le workflow lors d'un push sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Spécifiez la version de Node.js compatible avec votre projet

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Générer le build
      - name: Build project
        run: npm run build

      # Étape 5 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Utilisation du token d'authentification GitHub
          publish_dir: ./dist # Dossier contenant les fichiers à déployer
